# 网站信息
title: My Awesome Blog
description: Sharing thoughts and ideas about life, tech, and more.
baseurl: "" # 根目录（如果不是顶层页面，可以设置为子目录，例如 /blog）
url: "https://<your-github-username>.github.io" # 你的网站 URL

# 作者信息
author:
  name: Your Name
  email: your.email@example.com
  social:
    twitter: your_twitter_username
    github: your_github_username

# 主题设置
theme: minima # 使用 Jekyll 默认主题

# Markdown 设置
markdown: kramdown
kramdown:
  input: GFM # 支持 GitHub 风格的 Markdown
  hard_wrap: false

# 插件
plugins:
  - jekyll-sitemap    # 自动生成网站地图
  - jekyll-feed       # RSS 订阅
  - jekyll-seo-tag    # SEO 优化
  - jekyll-paginate   # 分页支持

# 分页
paginate: 5 # 每页文章数
paginate_path: "/page:num/"

# 标签页面
collections:
  posts:
    output: true
    permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      tags: []

# 高亮代码
highlighter: rouge
highlight:
  theme: github # 代码高亮样式（可改为 solarized, monokai 等）

# 导航栏配置
navbar:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about.html"
  - title: "Tags"
    url: "/tags.html"

# 本地开发端口
port: 4000

# 输出配置
exclude: ["README.md", "Gemfile", "Gemfile.lock"]
