baseurl: "/docs"

title: Coyote Blog
author: Coyote
description: Sharing thoughts and ideas about life, tech, and more.
show_downloads: false

github_username:  coyote

publications: True
blog: False


remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-scholar
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
  
bootstrap:
  assets: true




