remote_theme: pages-themes/cayman@v0.2.0

title: Coyote Blog
description: Sharing thoughts and ideas about life, tech, and more.
show_downloads: false


theme_settings:
  title: Coytoe Blog

  experience_title: EXPERIENCE
  interests_title: RESEARCH INTERESTS
  skills_title: SKILLS
  #awards_title: AWARDS
  projects_title: PROJECTS
  recentpubs_title: RECENT PUBLICATIONS

plugins:
  - jekyll-scholar
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
  
bootstrap:
  assets: true




